//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomClient
    {
        public Nullable<int> ID_CLIENT { get; set; }
        public Nullable<int> ID_ROOM { get; set; }
        public int ID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
